
import path from "node:path";

const comp = (name: string) => path.resolve(__dirname, `src/${name}.tsx`);

export function getComponentEntries(): Record<string, string> {
	return {
		"accordion": comp("accordion"),
		"alert-dialog": comp("alert-dialog"),
		"alert": comp("alert"),
		"avatar": comp("avatar"),
		"badge": comp("badge"),
		"blockquote": comp("blockquote"),
		"breadcrumb": comp("breadcrumb"),
		"button": comp("button"),
		"callout": comp("callout"),
		"caption": comp("caption"),
		"card": comp("card"),
		"carousel": comp("carousel"),
		"chart": comp("chart"),
		"checkbox": comp("checkbox"),
		"collapsible": comp("collapsible"),
		"columns": comp("columns"),
		"command": comp("command"),
		"dashboard-badge": comp("dashboard-badge"),
		"definition": comp("definition"),
		"dialog": comp("dialog"),
		"dropdown": comp("dropdown"),
		"hover-card": comp("hover-card"),
		"image": comp("image"),
		"input": comp("input"),
		"label": comp("label"),
		"link": comp("link"),
		"login-button": comp("login-button"),
		"multi-select": comp("multi-select"),
		"page-title": comp("page-title"),
		"pager": comp("pager"),
		"popover": comp("popover"),
		"progress": comp("progress"),
		"prose": comp("prose"),
		"radio": comp("radio"),
		"scroll-area": comp("scroll-area"),
		"select": comp("select"),
		"separator": comp("separator"),
		"sheet": comp("sheet"),
		"sidebar": comp("sidebar"),
		"skeleton": comp("skeleton"),
		"spinner": comp("spinner"),
		"status-button": comp("status-button"),
		"steps": comp("steps"),
		"switch": comp("switch"),
		"table": comp("table"),
		"tabs": comp("tabs"),
		"textarea": comp("textarea"),
		"toggle-group": comp("toggle-group"),
		"toggle": comp("toggle"),
		"tooltip": comp("tooltip"),
	};
}
